TP3BanqueAlaTemin-war/src/java/fr/av/mbds/ConstantMBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.av.mbds;

import fr.av.mbds.enums.ERolePersonne;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;

/**
 *
 * @author valentin
 */
@Named(value = "constantMBean")
@ApplicationScoped
public class ConstantMBean {
    
    public ERolePersonne[] getRoleValues(){
        return ERolePersonne.values();
    }
}

TP3BanqueAlaTemin-war/web/restrict/commun/ActionCompteBancaire.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <body>

        <ui:composition template="../../templates/template_default.xhtml">

            <ui:define name="metadata">
                <f:metadata>  
                    <f:viewParam name="idCompteBancaire" value="#{actionCompteBancaireMBean.idCompteBancaire}"  
                                 required="true"/>  
                    <f:viewAction action="#{actionCompteBancaireMBean.loadCompteBancaire}"/>
                </f:metadata>  
            </ui:define>

            <ui:define name="content">
                <h1>Ajouter/Retirer de l'argent du compte : #{actionCompteBancaireMBean.compteBancaire.id}</h1>
                <h:messages globalOnly="true" errorClass="text-danger" infoClass="text-success"/>
                <h:form>
                    <div class="col-md-3 col-xs-12">
                        <div class="form-group">
                            <label for="nbAjout">Ajouter de l'argent : </label>
                            <h:inputText id="nbAjout" class="form-control" value="#{actionCompteBancaireMBean.nbAjout}" />
                        </div>
                        <div class="form-group">
                            <label for="nbRetirer">Retirer de l'argent : </label>
                            <h:inputText id="nbRetirer" class="form-control" value="#{actionCompteBancaireMBean.nbRetirer}" />
                        </div>
                        <h:commandButton id="update" class="btn btn-success mr-2" value="Mettre à jour" action="#{actionCompteBancaireMBean.update}"/>
                    </div>
                </h:form>
            </ui:define>

        </ui:composition>

    </body>
</html>

TP3BanqueAlaTemin-war/web/restrict/commun/AjoutEditPersonne.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core">

    <body>
        <ui:composition template="./../../templates/template_default.xhtml">

            <ui:define name="metadata">
                <f:metadata>  
                    <f:viewParam name="idPersonne" value="#{ajoutPersonneMBean.idPersonne}"/>  
                    <f:viewAction action="#{ajoutPersonneMBean.loadPersonne}"/>  
                </f:metadata>  
            </ui:define>

            <ui:define name="content">
                <h:form>
                    <h1><h:outputText value="Ajout/Édition d'une personne"/></h1>
                    <h:messages globalOnly="true" errorClass="text-danger" infoClass="text-success"/>
                    <div class="col-md-3 col-xs-12">
                        <div class="form-group">
                            <label for="nom">Nom:</label>
                            <h:inputText id="nom" value="#{ajoutPersonneMBean.nouvellePersonne.nom}" 
                                         title="nom" class="form-control" required="true" 
                                         requiredMessage="Nom requis"/>
                            <h:message for="nom" errorClass="text-danger" />
                        </div>
                        <div class="form-group">
                            <label for="prenom">Prénom:</label>
                            <h:inputText id="prenom" value="#{ajoutPersonneMBean.nouvellePersonne.prenom}" 
                                         title="prenom" class="form-control" required="true" 
                                         requiredMessage="Prénom requis"/>
                            <h:message for="prenom" errorClass="text-danger" />
                        </div>
                        <div class="form-group">
                            <label for="motDePasse">Mot de passe:</label>
                            <h:inputSecret id="motDePasse" value="#{ajoutPersonneMBean.nouvellePersonne.motDePasse}" 
                                           title="motDePasse" class="form-control" required="true" 
                                           requiredMessage="Mot de passe requis"/>
                            <h:message for="motDePasse" errorClass="text-danger" />
                        </div>
                        <div class="form-group">
                            <label for="adresseMail">Email:</label>
                            <h:inputText id="adresseMail" value="#{ajoutPersonneMBean.nouvellePersonne.adresseMail}" title="adresseMail" 
                                         class="form-control" 
                                         required="true" requiredMessage="Adresse mail requis"
                                         validatorMessage="Adresse mail invalide">
                                <f:validateRegex
                                    pattern="^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$" />
                            </h:inputText>
                            <h:message for="adresseMail" errorClass="text-danger" />
                        </div>
                        <div class="form-group">
                            <label for="adresse">Adresse:</label>
                            <h:inputText id="adresse" value="#{ajoutPersonneMBean.nouvellePersonne.adresse}" 
                                         title="adresse" class="form-control" required="true" 
                                         requiredMessage="Adresse requis"/>
                            <h:message for="adresse" errorClass="text-danger" />
                        </div>
                        <div class="form-group">
                            <label for="ville">Ville:</label>
                            <h:inputText id="ville" value="#{ajoutPersonneMBean.nouvellePersonne.ville}" 
                                         title="ville" class="form-control" required="true" 
                                         requiredMessage="Ville requis"/>
                            <h:message for="ville" errorClass="text-danger" />
                        </div>
                        <c:if test='${ajoutPersonneMBean.idPersonne == null and utilisateur.hasRole("Administrateur")}'>
                            <div class="form-group">
                                <label for="role">Rôle:</label>
                                <h:selectOneMenu class="form-control"  value="#{ajoutPersonneMBean.role}"   
                                                 title="Type" required="true" requiredMessage="Type requis">   
                                    <f:selectItems value="#{constantMBean.roleValues}"  
                                                   var="item"   
                                                   itemLabel="#{item}" itemValue="#{item}" />  
                                </h:selectOneMenu> 
                            </div>
                        </c:if>
                        <c:if test='${ajoutPersonneMBean.idPersonne == null}'>
                            <h:commandButton value="Créer" class="btn btn-success mr-2" action="#{ajoutPersonneMBean.creerPersonne}"/> 
                        </c:if>
                        <c:if test="${ajoutPersonneMBean.idPersonne != null}">
                            <h:commandButton value="Modifier" class="btn btn-success mr-2" action="#{ajoutPersonneMBean.modifierPersonne}"/> 
                        </c:if>
                    </div>
                </h:form>
            </ui:define>

        </ui:composition>

    </body>
</html>

TP3BanqueAlaTemin-war/web/restrict/commun/TransfertCompteBancaire.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <body>

        <ui:composition template="../../templates/template_default.xhtml">

            <ui:define name="content">
                <h1>Transfert</h1>
                <h:messages globalOnly="true" errorClass="text-danger" />
                <h:form>
                    <div class="col-md-3 col-xs-12">
                        <div class="form-group">
                            <label for="srcComptebancaire">Transfert du compte : </label>
                            <h:selectOneMenu class="form-control" id="srcCompteBancaire" value="#{transfertCompteBancaireMBean.srcCompteBancaire}"   
                                             title="DiscountCode" required="true" requiredMessage="Source Compte Bancaire est indispensable" 
                                             converter="#{transfertCompteBancaireMBean.compteBancaireConverter}">   
                                <f:selectItems value="#{transfertCompteBancaireMBean.srcListCompteBancaire}"  
                                               var="item"   
                                               itemLabel="#{item.id}" itemValue="#{item}" />  
                            </h:selectOneMenu>
                        </div>
                        <div class="form-group">
                            <label for="destComptebancaire">au compte : </label>
                            <h:selectOneMenu class="form-control" id="destCompteBancaire" value="#{transfertCompteBancaireMBean.destCompteBancaire}"   
                                             title="DiscountCode" required="true" requiredMessage="Source Compte Bancaire est indispensable" 
                                             converter="#{transfertCompteBancaireMBean.compteBancaireConverter}">   
                                <f:selectItems value="#{transfertCompteBancaireMBean.destListCompteBancaire}"  
                                               var="item"   
                                               itemLabel="#{item.id}" itemValue="#{item}" />  
                            </h:selectOneMenu>
                        </div>
                        <div class="form-group">
                            <label for="montant">Montant du transfert :</label>
                            <h:inputText class="form-control" id="montant" value="#{transfertCompteBancaireMBean.montant}" />
                            <h:message id="montantMessage" for="montant" errorClass="text-danger" />
                        </div>
                        <h:commandButton id="transfert" class="btn btn-success mr-2" value="Transfert" action="#{transfertCompteBancaireMBean.transfert}"/>
                    </div>
                </h:form>
            </ui:define>

        </ui:composition>

    </body>
</html>