TP3BanqueAlaTemin-war/src/java/fr/av/mbds/AjoutCompteBancaireMBean.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.av.mbds;

import fr.av.mbds.entities.Client;
import fr.av.mbds.entities.CompteBancaire;
import fr.av.mbds.sessions.GestionnaireClient;
import fr.av.mbds.sessions.GestionnaireDeCompteBancaire;
import java.io.Serializable;
import java.util.List;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.inject.Named;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.view.ViewScoped;

/**
 *
 * @author Alison Temin
 */
@Named(value = "ajoutCompteBancaireMBean")
@ViewScoped
public class AjoutCompteBancaireMBean implements Serializable {

    @EJB
    private GestionnaireClient gestionnaireClient;
    @EJB
    private GestionnaireDeCompteBancaire gestionnaireDeCompteBancaire;
    private CompteBancaire compteBancaire = new CompteBancaire();

    private Converter clientConverter = new Converter() {

        @Override
        public Object getAsObject(FacesContext context, UIComponent component, String value) {
            Client cb = gestionnaireClient.getClient(Long.parseLong(value));
            return cb;
        }

        @Override
        public String getAsString(FacesContext context, UIComponent component, Object value) {
            Client mm = (Client) value;
            return mm.getId().toString();
        }
    };
    
    @EJB
    private GestionnaireClient clientManager;

    public Converter getClientConverter() {
        return clientConverter;
    }

    public List<Client> getAllClients() {
        return clientManager.getClients();
    }

    public CompteBancaire getCompteBancaire() {
        return compteBancaire;
    }

    public String create() {
        gestionnaireDeCompteBancaire.creerCompte(compteBancaire);
        FacesContext.getCurrentInstance().addMessage(null, 
                new FacesMessage(FacesMessage.SEVERITY_INFO, "Compte créé avec succès !", null));
        return "";
    }

    /**
     * Creates a new instance of AjoutCompteBancaireMBean
     */

    public AjoutCompteBancaireMBean() {
    }

}

TP3BanqueAlaTemin-war/web/restrict/admin/AdministrateurList.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <body>

        <ui:composition template="./../../templates/template_default.xhtml">

            <ui:define name="content">
                <h1>Liste des administrateurs</h1> 
                <f:view>
                    <h:form id="form">
                        <p:dataTable paginator="true" rows="10" value="#{administrateurMBean.lazyModel}" var="item"
                                     paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
                                     rowsPerPageTemplate="5,10,15" id="clientTable" lazy="true"
                                     selection="#{administrateurMBean.selectedAdministrateur}"
                                     >
                            <p:column filterBy="#{item.id}">
                                <f:facet name="header">
                                    <h:outputText value="Id"/>
                                </f:facet>
                                <h:outputText value="#{item.id}"/>
                            </p:column>
                            <p:column filterBy="#{item.nom}">
                                <f:facet name="header">
                                    <h:outputText value="Nom"/>
                                </f:facet>
                                <h:outputText value="#{item.nom}"/>
                            </p:column>
                            <p:column filterBy="#{item.prenom}">
                                <f:facet name="header">
                                    <h:outputText value="Prenom"/>
                                </f:facet>
                                <h:outputText value="#{item.prenom}"/>
                            </p:column>
                        </p:dataTable>
                    </h:form>
                </f:view>
            </ui:define>

        </ui:composition>

    </body>
</html>

TP3BanqueAlaTemin-war/web/restrict/admin/AjoutCompteBancaire.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <body>

        <ui:composition template="../../templates/template_default.xhtml">

            <ui:define name="content">
                <f:view>
                    <h:form>
                        <h1><h:outputText value="Create/Edit"/></h1>
                        <h:messages globalOnly="true" errorClass="text-danger" infoClass="text-success"/>
                        <div class="col-md-3 col-xs-12">
                            <div class="form-group">
                                <label for="proprietaire">Propriétaire:</label>
                                <h:selectOneMenu class="form-control" id="proprietaire" value="#{ajoutCompteBancaireMBean.compteBancaire.proprietaire}"   
                                                 title="Proprietaire" required="true" requiredMessage="The Proprietaire field is required."  
                                                 converter="#{ajoutCompteBancaireMBean.clientConverter}">   
                                    <f:selectItems value="#{ajoutCompteBancaireMBean.allClients}"  
                                                   var="item"   
                                                   itemLabel="#{item.id}" itemValue="#{item}" />  
                                </h:selectOneMenu> 
                            </div>
                            <div class="form-group">
                                <label for="solde">Solde:</label>
                                <h:inputText id="solde" value="#{ajoutCompteBancaireMBean.compteBancaire.solde}" class="form-control" title="Solde" />
                            </div>
                        </div>
                        
                        <h:commandButton id="update" class="btn btn-success mr-2" value="Créer" action="#{ajoutCompteBancaireMBean.create}"/>  
                    </h:form>
                </f:view>

            </ui:define>

        </ui:composition>

    </body>
</html>

TP3BanqueAlaTemin-war/web/restrict/admin/ClientList.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <body>

        <ui:composition template="./../../templates/template_default.xhtml">

            <ui:define name="content">
                <h1>Liste des clients</h1>
                <p>
                    Cliquez sur une ligne d'un client pour afficher ses comptes bancaires
                </p>
                <f:view>
                    <h:form id="form">
                        <p:dataTable paginator="true" rows="10" value="#{clientMBean.lazyModel}" var="item"
                                     paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
                                     rowsPerPageTemplate="5,10,15" id="clientTable" lazy="true"
                                     selectionMode="single" selection="#{clientMBean.selectedClient}"
                                     >
                            <p:ajax event="rowSelect" listener="#{clientMBean.onRowSelect}" update=":form:clientDetails" oncomplete="PF('clientDialog').show()" />
                            <p:column filterBy="#{item.id}">
                                <f:facet name="header">
                                    <h:outputText value="Id"/>
                                </f:facet>
                                <h:outputText value="#{item.id}"/>
                            </p:column>
                            <p:column filterBy="#{item.nom}">
                                <f:facet name="header">
                                    <h:outputText value="Nom"/>
                                </f:facet>
                                <h:outputText value="#{item.nom}"/>
                            </p:column>
                            <p:column filterBy="#{item.prenom}">
                                <f:facet name="header">
                                    <h:outputText value="Prenom"/>
                                </f:facet>
                                <h:outputText value="#{item.prenom}"/>
                            </p:column>
                            <p:column filterBy="#{item.sonConseiller.nom}">
                                <f:facet name="header">
                                    <h:outputText value="Conseiller"/>
                                </f:facet>
                                <h:outputText value="#{item.sonConseiller.nom}"/>
                            </p:column>
                            <p:column>
                                <f:facet name="header">
                                    <h:outputText value="Action"/>
                                </f:facet>
                                <p:commandButton icon="ui-icon-arrowstop-1-w"
                                                 title="Assigner un conseiller"
                                                 action="#{clientMBean.setCibleAssignConseiller(item)}"
                                                 oncomplete="PF('assignerConseiller').show()"
                                                 update=":form:assignerConseiller"
                                                 />
                                <p:button icon="ui-icon-pencil"
                                          title="Modifier"
                                          outcome="#{personneMBean.showEditPersonne(item.id)}"/>
                                <p:commandButton icon="ui-icon-trash"
                                                 title="Supprimer ce compte"
                                                 actionListener="#{personneMBean.supprimerPersonne(item)}"
                                                 update=':form:clientTable'/>
                            </p:column>
                        </p:dataTable>
                        <p:dialog header="Détails du clients" widgetVar="clientDialog" modal="true" showEffect="fade" hideEffect="fade" resizable="true" width="50%">
                            <p:outputPanel id="clientDetails" style="text-align:center;">
                                <h2>Sa carte d'identitée</h2>
                                Identifiant: #{clientMBean.selectedClient.saCarte.identifiantNational}<br/>
                                Date de naissance: #{clientMBean.selectedClient.saCarte.dateNaissance}
                                <h2>Ses comptes bancaires</h2>
                                <p:dataTable paginator="true" rows="10" value="#{clientMBean.selectedClient.sesComptesBancaires}" var="item"
                                             paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
                                             rowsPerPageTemplate="5,10,15" id="listCompteBancaire"
                                             >
                                    <p:column sortBy="#{item.id}" filterBy="#{item.id}">
                                        <f:facet name="header">
                                            <h:outputText value="Id"/>
                                        </f:facet>
                                        <h:outputText value="#{item.id}"/>
                                    </p:column>
                                    <p:column sortBy="#{item.solde}" filterBy="#{item.solde}">
                                        <f:facet name="header">
                                            <h:outputText value="Solde"/>
                                        </f:facet>
                                        <h:outputText value="#{item.solde}"/>
                                    </p:column>
                                </p:dataTable>
                            </p:outputPanel>
                        </p:dialog>

                        <!-- Assigner un conseiller -->
                        <p:dialog header="Assigner un conseiller" widgetVar="assignerConseiller" modal="true" showEffect="fade" hideEffect="fade" resizable="true" width="50%">
                            <p:outputPanel id="assignerConseiller" style="text-align:center;" class="col-md-12">
                                <h1><h:outputText value="Assigner un conseiller au client : #{clientMBean.cibleAssignConseiller.nomComplet}"/></h1>
                                <div class="col-md-3 col-xs-12">
                                    <div class="form-group">
                                        <label for="conseiller">Conseiller:</label>
                                        <h:selectOneMenu class="form-control"  id="conseiller" value="#{clientMBean.selectedConseiller}"   
                                                         title="Conseiller" required="true" requiredMessage="Le champs 'Conseiller' est requis."  
                                                         converter="#{clientMBean.conseillerConverter}">   
                                            <f:selectItems value="#{clientMBean.listConseiller}"  
                                                           var="item"   
                                                           itemLabel="#{item.id}" itemValue="#{item}" />  
                                        </h:selectOneMenu>
                                    </div> 
                                </div>
                                <p:commandButton update=":form:clientTable" value="Assigner" action="#{clientMBean.assignerConseiller()}" oncomplete="PF('assignerConseiller').hide()"/>
                            </p:outputPanel>
                        </p:dialog>
                    </h:form>
                </f:view>
            </ui:define>

        </ui:composition>

    </body>
</html>

TP3BanqueAlaTemin-war/web/restrict/admin/CompteBancaireList.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui" >

    <body>

        <ui:composition template="../../templates/template_default.xhtml">
            <ui:define name="content">
                <h1>Liste des comptes bancaires</h1> 
                <f:view>
                    <h:form id="form">
                        <p>
                            Cliquez sur une ligne d'un compte bancaire pour afficher les opérations bancaires et les co-propriétaires de ce dernier.
                        </p>
                        <p:dataTable paginator="true" rows="10" value="#{compteBancaireMBean.lazyModel}" var="item"
                                     paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
                                     rowsPerPageTemplate="5,10,15" id="compteBancaireTable" lazy="true"
                                     selectionMode="single" selection="#{compteBancaireMBean.selectedCompteBancaire}"
                                     >
                            <p:ajax event="rowSelect" listener="#{compteBancaireMBean.onRowSelect}" update=":form:compteBancaireDetails" oncomplete="PF('compteBancaireDialog').show()" />
                            <p:column sortBy="#{item.id}" filterBy="#{item.id}">
                                <f:facet name="header">
                                    <h:outputText value="Id"/>
                                </f:facet>
                                <h:outputText value="#{item.id}"/>
                            </p:column>
                            <p:column filterBy="#{item.proprietaire.nom}">
                                <f:facet name="header">
                                    <h:outputText value="Nom"/>
                                </f:facet>
                                <h:outputText value="#{item.proprietaire.nom}"/>
                            </p:column>
                            <p:column filterBy="#{item.proprietaire.prenom}">
                                <f:facet name="header">
                                    <h:outputText value="Prenom"/>
                                </f:facet>
                                <h:outputText value="#{item.proprietaire.prenom}"/>
                            </p:column>
                            <p:column sortBy="#{item.solde}" filterBy="#{item.solde}">
                                <f:facet name="header">
                                    <h:outputText value="Solde"/>
                                </f:facet>
                                <h:outputText value="#{item.solde}"/>
                            </p:column>
                            <p:column exportable="false">
                                <f:facet name="header">
                                    <h:outputText value="Action"/>
                                </f:facet>
                                        <p:button outcome="#{compteBancaireMBean.showActionCompteBancaire(item.id)}" 
                                                  icon="ui-icon-transfer-e-w"
                                                  title="Ajouter ou retirer de l'argent"/>
                                <p:commandButton icon="ui-icon-trash"
                                                 title="Supprimer ce compte"
                                                 actionListener="#{compteBancaireMBean.deleteCompteBancaire(item)}"
                                                 update=':form:compteBancaireTable'/>
                            </p:column>
                        </p:dataTable>
                        Export
                        <h:commandLink>
                            <p:graphicImage library="image" name="pdf.svg" width="24"/>
                            <p:dataExporter type="pdf" target="compteBancaireTable" fileName="lesComptes" />
                        </h:commandLink>
                        
                        <!-- Liste des opérations bancaire et des co-propriétaires -->
                        <p:dialog header="Compte Bancaire : Détails" widgetVar="compteBancaireDialog" modal="true" showEffect="fade" hideEffect="fade" resizable="false" width="50%" height="500px">
                            <p:outputPanel id="compteBancaireDetails" style="text-align:center;">
                                
                                <h2>Liste des opérations</h2>
                                <p:dataTable paginator="true" rows="10" value="#{compteBancaireMBean.selectedCompteBancaire.sesOperations}" var="item"
                                             paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
                                             rowsPerPageTemplate="5,10,15" id="listOperations"
                                             >
                                    <p:column sortBy="#{item.createdAt}" filterBy="#{item.createdAt}">
                                        <f:facet name="header">
                                            <h:outputText value="Date"/>
                                        </f:facet>
                                        <h:outputText value="#{item.createdAt}">
                                            <f:converter converterId="localDateTimeConverter" />
                                        </h:outputText>
                                    </p:column>
                                    <p:column sortBy="#{item.typeOperation}" filterBy="#{item.typeOperation}">
                                        <f:facet name="header">
                                            <h:outputText value="Type opération"/>
                                        </f:facet>
                                        <h:outputText value="#{item.typeOperation}"/>
                                    </p:column>
                                    <p:column sortBy="#{item.montant}" filterBy="#{item.montant}">
                                        <f:facet name="header">
                                            <h:outputText value="Montant"/>
                                        </f:facet>
                                        <h:outputText value="- " rendered="#{item.typeOperation == 'DEBIT'}"/>
                                        <h:outputText value="#{item.montant}"/>
                                    </p:column>
                                </p:dataTable>

                                <h2>Liste des co-propriétaire</h2>
                                <p:dataTable paginator="true" rows="10" value="#{compteBancaireMBean.selectedCompteBancaire.coProprietaires}" var="item"
                                             paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
                                             rowsPerPageTemplate="5,10,15" id="listCoProprietaire"
                                             >
                                    <p:column filterBy="#{item.id}">
                                        <f:facet name="header">
                                            <h:outputText value="Id"/>
                                        </f:facet>
                                        <h:outputText value="#{item.id}"/>
                                    </p:column>
                                    <p:column filterBy="#{item.nom}">
                                        <f:facet name="header">
                                            <h:outputText value="Nom"/>
                                        </f:facet>
                                        <h:outputText value="#{item.nom}"/>
                                    </p:column>
                                    <p:column filterBy="#{item.prenom}">
                                        <f:facet name="header">
                                            <h:outputText value="Prenom"/>
                                        </f:facet>
                                        <h:outputText value="#{item.prenom}"/>
                                    </p:column>
                                    <p:column>
                                        <f:facet name="header">
                                            <h:outputText value="Action"/>
                                        </f:facet>
                                        <p:commandButton icon="ui-icon-trash"
                                                 update=":form:listCoProprietaire"
                                                 title="Supprimer des co-propriétaires"
                                                 actionListener="#{compteBancaireMBean.supprimerCoProprietaire(item, compteBancaireMBean.selectedCompteBancaire)}"/>
                                    </p:column>
                                </p:dataTable>
                            </p:outputPanel>
                        </p:dialog>
                    </h:form>
                </f:view>

            </ui:define>

        </ui:composition>

    </body>
</html>

TP3BanqueAlaTemin-war/web/restrict/admin/ConseillerList.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">

    <body>

        <ui:composition template="./../../templates/template_default.xhtml">

            <ui:define name="content">
                <h1>Liste des conseillers</h1> 
                <p>
                    Cliquez sur une ligne d'un conseiller pour afficher les clients qui lui sont attribués
                </p>
                <f:view>
                    <h:form id="form">
                        <p:dataTable paginator="true" rows="10" value="#{conseillerMBean.lazyModel}" var="item"
                                     paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
                                     rowsPerPageTemplate="5,10,15" id="conseillerTable" lazy="true"
                                     selectionMode="single" selection="#{conseillerMBean.selectedConseiller}"
                                     >
                            <p:ajax event="rowSelect" listener="#{conseillerMBean.onRowSelect}" update=":form:conseillerDetails" oncomplete="PF('conseillerDialog').show()" />
                            <p:column filterBy="#{item.id}">
                                <f:facet name="header">
                                    <h:outputText value="Id"/>
                                </f:facet>
                                <h:outputText value="#{item.id}"/>
                            </p:column>
                            <p:column filterBy="#{item.nom}">
                                <f:facet name="header">
                                    <h:outputText value="Nom"/>
                                </f:facet>
                                <h:outputText value="#{item.nom}"/>
                            </p:column>
                            <p:column filterBy="#{item.prenom}">
                                <f:facet name="header">
                                    <h:outputText value="Prenom"/>
                                </f:facet>
                                <h:outputText value="#{item.prenom}"/>
                            </p:column>
                            <p:column>
                                <f:facet name="header">
                                    <h:outputText value="Action"/>
                                </f:facet>
                                <p:button icon="ui-icon-pencil"
                                          title="Modifier"
                                          outcome="#{personneMBean.showEditPersonne(item.id)}"/>
                                <p:commandButton icon="ui-icon-trash"
                                                 title="Supprimer ce compte"
                                                 actionListener="#{conseillerMBean.supprimerConseiller(item)}"
                                                 update=':form:conseillerTable'/>
                            </p:column>
                        </p:dataTable>
                        <p:dialog header="Détails du conseiller" widgetVar="conseillerDialog" modal="true" showEffect="fade" hideEffect="fade" resizable="true" width="50%">
                            <p:outputPanel id="conseillerDetails" style="text-align:center;">
                                <p:dataTable paginator="true" rows="10" value="#{conseillerMBean.selectedConseiller.sesClients}" var="item"
                                             paginatorTemplate="{RowsPerPageDropdown} {FirstPageLink} {PreviousPageLink} {CurrentPageReport} {NextPageLink} {LastPageLink}"
                                             rowsPerPageTemplate="5,10,15" id="listClient"
                                             >
                                    <p:column sortBy="#{item.id}" filterBy="#{item.id}">
                                        <f:facet name="header">
                                            <h:outputText value="Id"/>
                                        </f:facet>
                                        <h:outputText value="#{item.id}"/>
                                    </p:column>
                                    <p:column sortBy="#{item.nom}" filterBy="#{item.nom}">
                                        <f:facet name="header">
                                            <h:outputText value="Nom"/>
                                        </f:facet>
                                        <h:outputText value="#{item.nom}"/>
                                    </p:column>
                                    <p:column sortBy="#{item.prenom}" filterBy="#{item.prenom}">
                                        <f:facet name="header">
                                            <h:outputText value="Prénom"/>
                                        </f:facet>
                                        <h:outputText value="#{item.prenom}"/>
                                    </p:column>


                                </p:dataTable>
                            </p:outputPanel>
                        </p:dialog>
                    </h:form>
                </f:view>
            </ui:define>

        </ui:composition>

    </body>
</html>